# Generated by Django 5.0 on 2024-01-02 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 15, 57, 26, 73412, tzinfo=datetime.timezone.utc)),
        ),
    ]
