# Generated by Django 5.0 on 2024-01-02 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 16, 14, 3, 546095, tzinfo=datetime.timezone.utc)),
        ),
    ]
