# Generated by Django 5.0.1 on 2024-01-03 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_is_active_alter_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 17, 41, 8, 204044, tzinfo=datetime.timezone.utc)),
        ),
    ]
